# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9ea1cea8fbe5a22109e7c298e22913ed239edb0b9dfde91a7fd81f0f62d844cb517d4b588f2d75d7d4a362e5939fa4ed6eec20ee5d99bb20cd5c8bc2c05da43

test:
  secret_key_base: 762dcab9bf2a4e79aa45abbc1f2b2e47f585fd9c7b78cd6a3f6b873fc826776bd5065c4f2c9d8c3077166ef055d7b14b907e85313f23e0eb02e8a1a6f9d2179d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
